import {
  GENERIC_CLICK_PRIMARY_PITCH,
  GENERIC_CLICK_SECONDARY_PITCH,
  mapSimplePercussionElementPitchClasses,
} from "@/lib/services/rhythm-service/kits/generic-click";
import type {
  SampleKitDefinition,
  SampleKitEntry,
} from "@/lib/services/rhythm-service/kits/types";

export const MELODIC_TOM_SAMPLE_KIT: Record<number, SampleKitEntry> = {
  21: { kind: "file", fileName: "A0.mp3" },
  22: { kind: "file", fileName: "Bb0.mp3" },
  23: { kind: "file", fileName: "B0.mp3" },
  24: { kind: "file", fileName: "C1.mp3" },
  25: { kind: "file", fileName: "Db1.mp3" },
  26: { kind: "file", fileName: "D1.mp3" },
  27: { kind: "file", fileName: "Eb1.mp3" },
  28: { kind: "file", fileName: "E1.mp3" },
  29: { kind: "file", fileName: "F1.mp3" },
  30: { kind: "file", fileName: "Gb1.mp3" },
  31: { kind: "file", fileName: "G1.mp3" },
  32: { kind: "file", fileName: "Ab1.mp3" },
  33: { kind: "file", fileName: "A1.mp3" },
  34: { kind: "file", fileName: "Bb1.mp3" },
  35: { kind: "file", fileName: "B1.mp3" },
  36: { kind: "file", fileName: "C2.mp3" },
  37: { kind: "file", fileName: "Db2.mp3" },
  38: { kind: "file", fileName: "D2.mp3" },
  39: { kind: "file", fileName: "Eb2.mp3" },
  40: { kind: "file", fileName: "E2.mp3" },
  41: { kind: "file", fileName: "F2.mp3" },
  42: { kind: "file", fileName: "Gb2.mp3" },
  43: { kind: "file", fileName: "G2.mp3" },
  44: { kind: "file", fileName: "Ab2.mp3" },
  45: { kind: "file", fileName: "A2.mp3" },
  46: { kind: "file", fileName: "Bb2.mp3" },
  47: { kind: "file", fileName: "B2.mp3" },
  48: { kind: "file", fileName: "C3.mp3" },
  49: { kind: "file", fileName: "Db3.mp3" },
  50: { kind: "file", fileName: "D3.mp3" },
  51: { kind: "file", fileName: "Eb3.mp3" },
  52: { kind: "file", fileName: "E3.mp3" },
  53: { kind: "file", fileName: "F3.mp3" },
  54: { kind: "file", fileName: "Gb3.mp3" },
  55: { kind: "file", fileName: "G3.mp3" },
  56: { kind: "file", fileName: "Ab3.mp3" },
  57: { kind: "file", fileName: "A3.mp3" },
  58: { kind: "file", fileName: "Bb3.mp3" },
  59: { kind: "file", fileName: "B3.mp3" },
  60: { kind: "file", fileName: "C4.mp3" },
  61: { kind: "file", fileName: "Db4.mp3" },
  62: { kind: "file", fileName: "D4.mp3" },
  63: { kind: "file", fileName: "Eb4.mp3" },
  64: { kind: "file", fileName: "E4.mp3" },
  65: { kind: "file", fileName: "F4.mp3" },
  66: { kind: "file", fileName: "Gb4.mp3" },
  67: { kind: "file", fileName: "G4.mp3" },
  68: { kind: "file", fileName: "Ab4.mp3" },
  69: { kind: "file", fileName: "A4.mp3" },
  70: { kind: "file", fileName: "Bb4.mp3" },
  71: { kind: "file", fileName: "B4.mp3" },
  72: { kind: "file", fileName: "C5.mp3" },
  73: { kind: "file", fileName: "Db5.mp3" },
  74: { kind: "file", fileName: "D5.mp3" },
  75: { kind: "file", fileName: "Eb5.mp3" },
  76: { kind: "file", fileName: "E5.mp3" },
  77: { kind: "file", fileName: "F5.mp3" },
  78: { kind: "file", fileName: "Gb5.mp3" },
  79: { kind: "file", fileName: "G5.mp3" },
  80: { kind: "file", fileName: "Ab5.mp3" },
  81: { kind: "file", fileName: "A5.mp3" },
  82: { kind: "file", fileName: "Bb5.mp3" },
  83: { kind: "file", fileName: "B5.mp3" },
  84: { kind: "file", fileName: "C6.mp3" },
  85: { kind: "file", fileName: "Db6.mp3" },
  86: { kind: "file", fileName: "D6.mp3" },
  87: { kind: "file", fileName: "Eb6.mp3" },
  88: { kind: "file", fileName: "E6.mp3" },
  89: { kind: "file", fileName: "F6.mp3" },
  90: { kind: "file", fileName: "Gb6.mp3" },
  91: { kind: "file", fileName: "G6.mp3" },
  92: { kind: "file", fileName: "Ab6.mp3" },
  93: { kind: "file", fileName: "A6.mp3" },
  94: { kind: "file", fileName: "Bb6.mp3" },
  95: { kind: "file", fileName: "B6.mp3" },
  96: { kind: "file", fileName: "C7.mp3" },
  97: { kind: "file", fileName: "Db7.mp3" },
  98: { kind: "file", fileName: "D7.mp3" },
  99: { kind: "file", fileName: "Eb7.mp3" },
  100: { kind: "file", fileName: "E7.mp3" },
  101: { kind: "file", fileName: "F7.mp3" },
  102: { kind: "file", fileName: "Gb7.mp3" },
  103: { kind: "file", fileName: "G7.mp3" },
  104: { kind: "file", fileName: "Ab7.mp3" },
  105: { kind: "file", fileName: "A7.mp3" },
  106: { kind: "file", fileName: "Bb7.mp3" },
  107: { kind: "file", fileName: "B7.mp3" },
  108: { kind: "file", fileName: "C8.mp3" },
};

export const MELODIC_TOM_KIT: SampleKitDefinition = {
  entries: MELODIC_TOM_SAMPLE_KIT,
  getDefaultFallbackPitch: (hasAccent) =>
    hasAccent ? GENERIC_CLICK_PRIMARY_PITCH : GENERIC_CLICK_SECONDARY_PITCH,
  getFallbackPitchesFromElementPitchClasses:
    mapSimplePercussionElementPitchClasses,
  resolvePlaybackPitch: (pitch) => pitch,
};
