/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Source: Postgres catalogs (schema: public)
 * Generated by: oosync/src/codegen-schema.ts
 */

import type { BrowserSqliteDatabase } from "oosync/runtime/browser-sqlite";
import { createBrowserSqliteClient } from "oosync/runtime/browser-sqlite";
// eslint-disable-next-line import/no-unresolved
import sqlWasmUrl from "sql.js/dist/sql-wasm.wasm?url";
import * as schema from "../../../drizzle/schema-sqlite";
import {
  SYNCABLE_TABLES,
  TABLE_REGISTRY,
  TABLE_SYNC_ORDER,
  TABLE_TO_SCHEMA_KEY,
} from "../../../shared/table-meta";
import { browserSqliteHooks } from "./oosync-browser-sqlite-hooks";

export const browserSqliteClient = createBrowserSqliteClient({
  schema,
  syncPushQueue: schema.syncPushQueue,
  syncSchema: {
    syncableTables: SYNCABLE_TABLES,
    tableRegistry: TABLE_REGISTRY,
    tableSyncOrder: TABLE_SYNC_ORDER,
    tableToSchemaKey: TABLE_TO_SCHEMA_KEY,
  },
  sqlWasmUrl,
  hooks: browserSqliteHooks,
  diagnosticsEnabled: import.meta.env.VITE_SYNC_DIAGNOSTICS === "true",
  storage: {
    indexedDbName: "tunetrees-storage",
    indexedDbStore: "databases",
    dbKeyPrefix: "tunetrees-db",
    dbVersionKeyPrefix: "tunetrees-db-version",
    outboxBackupKeyPrefix: "tunetrees-outbox-backup",
    lastSyncTimestampKeyPrefix: "TT_LAST_SYNC_TIMESTAMP",
  },
  databaseVersion: 13,
  schemaVersion: "2.0.6-add-media-assets",
  migrationFiles: [
    "/drizzle/migrations/sqlite/0000_lowly_obadiah_stane.sql",
    "/drizzle/migrations/sqlite/0001_thin_chronomancer.sql",
    "/drizzle/migrations/sqlite/0002_nappy_roland_deschain.sql",
    "/drizzle/migrations/sqlite/0003_friendly_cerebro.sql",
    "/drizzle/migrations/sqlite/0005_add_display_order.sql",
    "/drizzle/migrations/sqlite/0006_add_auto_schedule_new.sql",
    "/drizzle/migrations/sqlite/0007_add_hybrid_fields.sql",
    "/drizzle/migrations/sqlite/0008_add_sync_change_log.sql",
    "/drizzle/migrations/sqlite/0009_add_view_column_meta.sql",
    "/drizzle/migrations/sqlite/0009_add_plugins.sql",
    "/drizzle/migrations/sqlite/0010_add_plugin_goals.sql",
    "/drizzle/migrations/sqlite/0011_rename_user_profile_id.sql",
    "/drizzle/migrations/sqlite/0012_rename_playlist_to_repertoire.sql",
    "/drizzle/migrations/sqlite/0013_add_goal_table.sql",
    "/drizzle/migrations/sqlite/0014_add_media_assets.sql",
  ],
  forceResetQueryParams: [
    { key: "reset", value: "true" },
    { key: "migrate", value: "uuid" },
  ],
  testConfig: {
    testApiWindowProperty: "__ttTestApi",
    clearInProgressWindowProperty: "__ttE2eIsClearing",
    persistWindowHookProperty: "__persistDbForTest",
  },
});

export const initializeDb = browserSqliteClient.initializeDb;
export const getDb = browserSqliteClient.getDb;
export const persistDb = browserSqliteClient.persistDb;
export const closeDb = browserSqliteClient.closeDb;
export const clearDb = browserSqliteClient.clearDb;
export const setupAutoPersist = browserSqliteClient.setupAutoPersist;
export const getSqliteInstance = browserSqliteClient.getSqliteInstance;
export const getSqlJsDebugInfo = browserSqliteClient.getSqlJsDebugInfo;
export const getClientSqliteDebugState = browserSqliteClient.getDebugState;
export const loadOutboxBackupForUser =
  browserSqliteClient.loadOutboxBackupForUser;
export const clearOutboxBackupForUser =
  browserSqliteClient.clearOutboxBackupForUser;

export { schema };
export type SqliteDatabase = BrowserSqliteDatabase;
export type Schema = typeof schema;
