sonar.organization=sboagy
sonar.projectKey=sboagy_tunetrees
sonar.sources=src,e2e,tests,worker
sonar.exclusions=public/sql-wasm/**,e2e/tests-sboagy-1/sboagy-001-queue-handling.spec.ts,__notes/**,**/*.sql,**/.wrangler/**,**/node_modules/**

# Point SonarQube to the Vitest coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info