sonar.organization=sboagy
sonar.projectKey=sboagy_tunetrees
sonar.sources=.
sonar.exclusions=public/sql-wasm/**,e2e/tests-sboagy-1/sboagy-001-queue-handling.spec.ts,__notes/**

# Point SonarQube to the Vitest coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info