export type Tune = {
  id: number;
  title: string;
  type: string;
  structure: string;
  mode: string;
  incipit: string;
  learned: string;
  practiced: string;
  quality: string;
  easiness: number;
  interval: number;
  repetitions: number;
  review_date: string;
  backup_practiced: string;
  notes_private: string;
  notes_public: string;
  tags: string;
  recallEval: string;
};
