/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Source: Postgres catalogs (schema: public)
 * Generated by: oosync/src/codegen-schema.ts
 */

export * from "./schema-sqlite.generated";

import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * Client-side outbox used by the oosync runtime.
 */
export const syncPushQueue = sqliteTable(
  "sync_push_queue",
  {
    id: text("id").primaryKey().notNull(),
    tableName: text("table_name").notNull(),
    rowId: text("row_id").notNull(),
    operation: text("operation").notNull(),
    status: text("status").default("pending").notNull(),
    changedAt: text("changed_at").notNull(),
    syncedAt: text("synced_at"),
    attempts: integer("attempts").default(0).notNull(),
    lastError: text("last_error"),
  },
  (t) => [
    index("idx_push_queue_status_changed").on(t.status, t.changedAt),
    index("idx_push_queue_table_row").on(t.tableName, t.rowId),
  ]
);
