INSERT INTO main.genre (id, name, region, description) VALUES
('ITRAD', 'Irish Traditional Music', 'Ireland', 'A centuries-old tradition of folk music featuring instruments like the fiddle, flute, tin whistle, and bodhrán.'),
('OTIME', 'Old-Time Music', 'Southern Appalachia, USA', 'Traditional American folk music with roots in British Isles ballads and dance tunes, often played on fiddle, banjo, and guitar.'),
('BGRA', 'Bluegrass Music', 'Southern Appalachia, USA', 'Upbeat American roots music characterized by fast tempos, intricate vocal harmonies, and instrumental virtuosity, often featuring banjo, fiddle, mandolin, guitar, and upright bass.'),
('CONTRA', 'Contra Dance Music', 'New England, USA', 'Lively folk dance music with roots in English country dances, typically played on fiddle, piano, guitar, and bass.'),
('FRCAN', 'French-Canadian Folk Music', 'Quebec, Canada', 'Traditional music of Quebec with influences from Celtic and European traditions, often featuring fiddle, accordion, and spoons.'),
('SCOT', 'Scottish Traditional Music', 'Scotland', 'Folk music tradition featuring bagpipes, fiddle, and harp, with strong connections to dance and storytelling.'),
('NFLD', 'Music of Newfoundland and Labrador', 'Newfoundland and Labrador, Canada', 'Unique folk music tradition with Irish, English, and French influences, often featuring fiddle, accordion, and bodhrán.'),
('KLEZM', 'Klezmer Music', 'Eastern Europe', 'Lively, expressive music of Ashkenazi Jews, often featuring clarinet, violin, and accordion.'),
('FLAM', 'Flamenco', 'Spain', 'Passionate music and dance tradition from Andalusia, featuring guitar, singing, and handclapping.'),
('BLUES', 'Blues', 'American South, USA',  'Influential genre with roots in African musical traditions, characterized by soulful vocals, guitar, and often a "call and response" pattern.'),
('CAJUN', 'Cajun Music', 'Louisiana, USA', 'Upbeat dance music with French and Acadian influences, typically featuring fiddle, accordion, and triangle.'),
('TEXMX', 'Tex-Mex Music', 'Texas, USA', 'Lively blend of Mexican and American influences, often featuring accordion, bajo sexto (a 12-string guitar), and drums.'),
('SAMBA', 'Samba', 'Brazil', 'Rhythmic music and dance with African roots, featuring drums, percussion, and often elaborate costumes.'),
('FADO', 'Fado', 'Portugal', 'Melancholic music tradition featuring expressive vocals and guitar, often reflecting themes of longing and fate.'),
('GAME', 'Gamelan', 'Indonesia', 'Ensemble music featuring metallophones, gongs, drums, and bamboo flutes, known for its intricate rhythms and interlocking melodies.');
