/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Source: Postgres catalogs (schema: public)
 * Generated by: oosync/src/codegen-schema.ts
 */

import createWorker from "oosync/worker";
import {
  SYNCABLE_TABLES,
  TABLE_REGISTRY_CORE,
} from "../../shared/generated/sync/table-meta.generated";
import { tables as schemaTables } from "./generated/schema-postgres.generated";
import { WORKER_SYNC_CONFIG } from "./generated/worker-config.generated";

export default createWorker({
  schemaTables,
  syncableTables: SYNCABLE_TABLES,
  tableRegistryCore: TABLE_REGISTRY_CORE,
  workerSyncConfig: WORKER_SYNC_CONFIG,
});
