"""due dilegence for changes from PRs

Revision ID: 5177d109a595
Revises: 6852fb7949e0
Create Date: 2025-07-23 14:23:51.311195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import view utilities from the local directory
import sys
import os
sys.path.insert(0, os.path.dirname(__file__) + "/..") 
from view_utils import create_views, drop_views


# revision identifiers, used by Alembic.
revision: str = '5177d109a595'
down_revision: Union[str, Sequence[str], None] = '6852fb7949e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_tune', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.Text(), server_default=sa.text("'recall'"), nullable=True))
        batch_op.add_column(sa.Column('technique', sa.Text(), nullable=True))


    # Recreate views with current schema
    drop_views()  # Drop existing views first
    create_views()  # Create views from target database
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_tune', schema=None) as batch_op:
        batch_op.drop_column('technique')
        batch_op.drop_column('goal')


    # Recreate views with current schema
    drop_views()  # Drop existing views first
    create_views()  # Create views from target database
    # ### end Alembic commands ###
