"""Add FSRS difficulty and step columns

Revision ID: fa13683caff1
Revises: baseline
Create Date: 2025-07-13 07:52:09.813291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Import view utilities for recreating views after schema changes
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

try:
    from view_utils import create_views_from_target_db
except ImportError:
    # Fallback if view_utils not available
    def create_views_from_target_db():
        print("Warning: view_utils not available, views not recreated")
        pass


# revision identifiers, used by Alembic.
revision: str = 'fa13683caff1'
down_revision: Union[str, Sequence[str], None] = 'baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('step', sa.Integer(), nullable=True))
        batch_op.create_index('practice_record_id_index', ['id'], unique=False)

    with op.batch_alter_table('prefs_spaced_repetition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_steps', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relearning_steps', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('enable_fuzzing', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
    
    # Recreate views after schema changes
    print("Recreating views after schema changes...")
    create_views_from_target_db()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prefs_spaced_repetition', schema=None) as batch_op:
        batch_op.drop_column('enable_fuzzing')
        batch_op.drop_column('relearning_steps')
        batch_op.drop_column('learning_steps')

    with op.batch_alter_table('practice_record', schema=None) as batch_op:
        batch_op.drop_index('practice_record_id_index')
        batch_op.drop_column('step')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
